<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class CurrencyCode {
    function getCurrencyCode($value): string
    {
        $map = [
            0 => "INR",
            1 => "USD",
            2 => "EUR",
            3 => "GBP",
            4 => "JPY",
            5 => "CHF",
            6 => "CAD",
            7 => "AUD",
            8 => "NZD",
            9 => "CNY",
            10 => "BRL",
            11 => "RUB",
            12 => "ZAR",
            13 => "MXN",
            14 => "SGD",
            15 => "HKD",
            16 => "NOK",
            17 => "SEK",
            18 => "DKK",
            19 => "TRY",
            20 => "AED",
            21 => "SAR",
            22 => "KRW",
            23 => "IDR",
            24 => "MYR",
            25 => "THB",
            26 => "PLN",
            27 => "HUF",
            28 => "CZK",
            29 => "ISK",
            30 => "CLP",
            31 => "COP",
            32 => "ARS",
            33 => "PEN",
            34 => "UAH",
            35 => "QAR",
            36 => "BHD",
            37 => "OMR",
            38 => "KWD",
            39 => "DZD",
            40 => "BBD",
            41 => "BZD",
            42 => "BMD",
            43 => "BTN",
            44 => "BOB",
            45 => "BAM",
            46 => "BWP",
            47 => "BND",
            48 => "BGN",
            49 => "MMK",
            50 => "BIF",
            51 => "KHR",
            52 => "XAF",
            53 => "XOF",
            54 => "CVE",
            55 => "KYD",
            56 => "XPF",
            57 => "CLF",
            58 => "CUP",
            59 => "CUC",
            60 => "DJF",
            61 => "DOP",
            62 => "EGP",
            63 => "ERN",
            64 => "ETB",
            65 => "FKP",
            66 => "FJD",
            67 => "GMD",
            68 => "GEL",
            69 => "GHS",
            70 => "GIP",
            71 => "GTQ",
            72 => "GNF",
            73 => "GYD",
            74 => "HTG",
            75 => "HNL",
            76 => "HRK",
            77 => "ILS",
            78 => "IMP",
            79 => "IRR",
            80 => "IQD",
            81 => "IRT",
            82 => "BDT",
        ];

        return $map[$value] ?? "Unknown Currency";
    }

}